### ISSUE TITLE
Renaming pyopenms-extra

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenMS/pyopenms-docs#269]
Rename `pyopenms-extra` repo.

**Options**
- `pyopenms-addons`
- `pyopenms-docs` 
- ?

**Tasks**
- [x] Update https://pyopenms.readthedocs.io/en/latest/, repository URL.
- [ ] Update About section of the repository. 
- [x] Add information in [README](https://github.com/OpenMS/pyopenms-extra#readme).
- [x] Update [25 references/usage](https://github.com/OpenMS/pyopenms-extra/search?p=1&q=pyopenms-extra) of `pyopenms-extra` in the repository, in code and as URL of the current repository.
- [x] Update [4 references/usage](https://github.com/search?q=org%3AOpenMS+pyopenms-extra+-repo%3AOpenMS%2Fpyopenms-extra&type=Code) of `pyopenms-extra` in OpenMS.

Ref: https://dictionary.cambridge.org/dictionary/english/extra.

**Comment by timosachsenberg** [comment]
maybe pyopenms-docs is fine. it includes examples etc. but I guess we can use that

**Comment by timosachsenberg** [comment]
@jpfeuffer do we use pyopenms-extra somewhere else? e.g. Jenkins / conda etc.? I don't think so right?
